# Generated by Django 5.1 on 2024-08-23 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('db_name', models.CharField(max_length=255)),
                ('db_user', models.CharField(max_length=255)),
                ('db_password', models.CharField(max_length=255)),
                ('db_host', models.CharField(max_length=255)),
                ('db_port', models.CharField(max_length=5)),
            ],
        ),
    ]
